app:
  host: localhost
  context: /message/v1
  port: 8081

aws:
  sns:
    prefix: dev
    region: us-west-1
    host: localhost
    port: 9911
    access-key: access-key
    secret-key: secret-key


events:
  user-message-event: user_message_topic
