app:
  host: localhost
  context: /message/v1
  port: 8081

aws:
  sns:
    prefix: dev
    region: us-east-1
    host: 0.0.0.0
    port: 9911
    access-key: access-key
    secret-key: secret-key


events:
  user-message-event: arn:aws:sns:us-east-1:123456789012:user_message_topic

user-service:
  base-uri: "http://localhost:8080/user/v1"
